## Введение в Pandas

Импорт Pandas:

In [1]:
import pandas as pd

Импорт в локальное пространство имен классов Series и DataFrame:

In [2]:
from pandas import Series, DataFrame

Две главные структуры данных в Pandas: Series и DataFrame.

# Объект Series

Series - одномерный, похожий на массив объект, который содержит последовательность данных и ассоциированный с ним
массив меток, который называется индексом.

Самый просто объект Series состоит только из массива данных:

In [3]:
import pandas as pd
from pandas import Series, DataFrame

obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

В строковом представлении Series, отображаемом в интерактивном режиме, индекс находится слева, a значения - справа.
Так как не был задан индекс для данных, по умолчанию создается индекс, который состоит из целых чисел от 0 до N. N -
это длина массива данных.

Получение представление самого массива и его индекса можно с помощью атрибутов values и index:

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index # как range(4)

RangeIndex(start=0, stop=4, step=1)

Создание объекта Series с индексом, который идентифицирует каждый элемент данных:

In [6]:
import pandas as pd
from pandas import Series, DataFrame

obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

В отличие от массивов NumPy, для выборки одного или нескольких значений можно использовать метки в индексе:

In [8]:
obj2['a']

np.int64(-5)

In [9]:
obj2['d'] = 6

In [10]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

В данном случае ['c', 'a', 'd'] интерпретируется как список индексов.

Функции NumPy, такие, как фильтрация с помощью булева массива, скалярное умножение или применение
математических функций, сохраняют связь между индексом и значением:

In [11]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [12]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [13]:
import numpy as np

np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Объект Series можно представить как упорядоченный словарь фиксированной длины, так как он отображает индекс на
данные. Его можно передавать функциям, ожидающим получить словарь:

In [14]:
'b' in obj2

True

In [15]:
'e' in obj2

False

Если имеется словарь Python, содержащий данные, то из него можно создать объект Series:

In [16]:
import pandas as pd
from pandas import Series, DataFrame

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Если передается только словарь, то в получившемся объекте Series ключи будут храниться в индексе по порядку:

In [17]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

В данном случае три значения, найденных в sdata, помещены в соответствующие им позиции, a для метки 'California'
никакого значения не нашлось, поэтому ей соответствует признак NaN (не число), которым в pandas обозначаются
отсутствующие значения. Поскольку строки 'Utah' не было в списке states, то ее нет и в результирующем объекте.

Для распознавания отсутствующих данных в pandas следует использовать функции isnull и notnull:

In [18]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

У объекта Series есть методы экземпляра:

In [20]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

При выполнении арифметических операций объект Series автоматически выравнивает данные по индексной метке:

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

У объекта Series, и у его индекса имеется атрибут name, тесно связанный с другими частями функциональности pandas:

In [24]:
obj4.name = 'population'

In [25]:
obj4.index.name = 'state'

In [26]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Индекс объекта Series можно изменить на месте с помощью присваивания:

In [27]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [28]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## Объект DataFrame

Объект DataFrame представляет табличную структуру данных, состоящую из упорядоченной коллекции столбцов, причем
типы значений (числовой, строковый, булев и т.д.) в разных столбцах могут различаться. В объекте DataFrame хранятся
два индекса: по строкам и по столбцам. Можно считать, что это словарь объектов Series, имеющих общий индекс. Внутри
объекта данные хранятся в виде одного или нескольких двумерных блоков, а не в виде списка, словаря или еще какой-нибудь коллекции одномерных массивов.

Есть много способов сконструировать объект DataFrame, один из самых распространенных – на основе словаря списков
одинаковой длины или массивов NumPy:

In [29]:
import pandas as pd
from pandas import Series, DataFrame

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

Получившемуся DataFrame автоматически будет назначен индекс, как и в случае Series, и столбцы расположатся по
порядку:

In [30]:
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


В Jupyter-блокноте объекты DataFrame отображаются в виде HTML-таблицы, более удобной для браузера. Для больших
объектов DataFrame метод head отбирает только первые пять строк:

In [31]:
frame.head()

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


Если задать последовательность столбцов, то столбцы DataFrame расположатся строго в указанном порядке:

In [32]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


Если запросить столбец, которого нет в data, то он будет заполнен значениями NaN:

In [33]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                            'five', 'six'])

In [34]:
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,NaN
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,NaN
five,2002,Nevada,2.9,NaN
six,2003,Nevada,3.2,NaN


In [35]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Столбец DataFrame можно извлечь как объект Series, воспользовавшись нотацией словарей или помощью атрибута:

Синтаксис frame2[column] работает для любого имени столбца, a frame2.column – только когда имя столбца – допустимое
имя переменной Python.

In [36]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [37]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Возвращенный объект Series имеет тот же индекс, что и DataFrame, a его атрибут name установлен соответствующим
образом.

Строки также можно извлечь по позиции или по имени с помощью специального атрибута loc (подробнее об этом ниже):

In [38]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

Столбцы можно модифицировать путем присваивания. Например, пустому столбцу 'debt' можно присвоить скалярное
значение или массив значений:

In [39]:
frame2['debt'] = 16.5
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,16.5
two,2001,Ohio,1.7,16.5
three,2002,Ohio,3.6,16.5
four,2001,Nevada,2.4,16.5
five,2002,Nevada,2.9,16.5
six,2003,Nevada,3.2,16.5


In [40]:
frame2['debt'] = np.arange(6.)
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,0.0
two,2001,Ohio,1.7,1.0
three,2002,Ohio,3.6,2.0
four,2001,Nevada,2.4,3.0
five,2002,Nevada,2.9,4.0
six,2003,Nevada,3.2,5.0


Когда столбцу присваивается список или массив, длина значения должна совпадать с длиной DataFrame. Если же
присваивается объект Series, то его метки будут точно выровнены с индексом DataFrame, a в «дырки» будут
вставлены значения NaN:

In [41]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,-1.2
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,-1.5
five,2002,Nevada,2.9,-1.7
six,2003,Nevada,3.2,NaN


Присваивание несуществующему столбцу приводит к созданию нового столбца. Для удаления столбцов служит ключевое
слово del, как и в обычном словаре.

Для демонстрации работы del добавим новый столбец булевых признаков, показывающих, находится ли в столбце state
значение 'Ohio':

In [42]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

,year,state,pop,debt,eastern
one,2000,Ohio,1.5,NaN,True
two,2001,Ohio,1.7,-1.2,True
three,2002,Ohio,3.6,NaN,True
four,2001,Nevada,2.4,-1.5,False
five,2002,Nevada,2.9,-1.7,False
six,2003,Nevada,3.2,NaN,False


Новый столбец нельзя создать, пользуясь синтаксисом frame2.eastern.

Для удаления этого столбца воспользуемся методом del:

In [43]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [44]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Столбец, возвращенный в ответ на запрос к DataFrame по индексу, является представлением, a не копией данных.
Следовательно, любые модификации этого объекта Series найдут отражение в DataFrame. Чтобы скопировать столбец,
нужно вызвать метод copy объекта Series.

Еще одна распространенная форма данных – словарь словарей:

In [45]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

Если передать вложенный словарь объекту DataFrame, то pandas интерпретирует ключи внешнего словаря как столбцы, a
ключи внутреннего словаря – как индексы строк:

In [46]:
frame3 = DataFrame(pop)
frame3

,Nevada,Ohio
2001,2.4,1.7
2002,2.9,3.6
2000,NaN,1.5


Объект DataFrame можно транспонировать (переставить строки и столбцы), воспользовавшись таким же синтаксисом, как для словаря
NumPy:

In [47]:
frame3.T

,2001,2002,2000
Nevada,2.4,2.9,NaN
Ohio,1.7,3.6,1.5


Ключи внутренних словарей объединяются и сортируются для образования индекса результата. Однако этого не
происходит, если индекс задан явно:

In [48]:
DataFrame(pop, index=[2001, 2002, 2003])

,Nevada,Ohio
2001,2.4,1.7
2002,2.9,3.6
2003,NaN,NaN


Словари объектов Series интерпретируются очень похоже:

In [49]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
DataFrame(pdata)

,Ohio,Nevada
2001,1.7,2.4
2002,3.6,2.9


Если у объектов, возвращаемых при обращении к атрибутам index и columns объекта DataFrame, установлен атрибут
name, то он также выводится:

In [50]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state,Nevada,Ohio
year,,
2001,2.4,1.7
2002,2.9,3.6
2000,NaN,1.5


Как и в случае Series, атрибут values возвращает данные, хранящиеся в DataFrame, в виде двумерного массива ndarray:

In [51]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

Если у столбцов DataFrame разные типы данных, то dtype массива values будет выбран так, чтобы охватить все столбцы:

In [52]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Задание 1

Приведите практические примеры всех аргументов конструктора DataFrame со своими примерами, перечисленных выше.
В отдельной строке перед примером необходимо дать описание каждого аргумента.

In [53]:
# Двумерный ndarray
arr = np.arange(20).reshape(4,5)
df = pd.DataFrame(arr, index=['0', '1', '2', '3'])
df

,0,1,2,3,4
0,0,1,2,3,4
1,5,6,7,8,9
2,10,11,12,13,14
3,15,16,17,18,19


In [54]:
# Словарь массивов
data = {'0': [0, 1, 2, 3, 4], '1': [5, 6, 7, 8, 9], '2': [10, 11, 12, 13, 14], '3': [15, 16, 17, 18, 19]}
df = pd.DataFrame(data)
df

,0,1,2,3
0,0,5,10,15
1,1,6,11,16
2,2,7,12,17
3,3,8,13,18
4,4,9,14,19


In [55]:
# Структурированный массив NumPy
arr = np.array([
    ("Name 1", 23, 10000),
    ("Name 2", 25, 20000),
    ("Name 3", 22, 30000)
])
df = pd.DataFrame(arr, columns=["Name", "Age", "Salary"])
df

,Name,Age,Salary
0,Name 1,23,10000
1,Name 2,25,20000
2,Name 3,22,30000


In [56]:
# Словарь объектов Series
data = {"Name 1": Series([1, 2, 3, 4]), "Name 2": Series([5, 6, 7, 8]),
                  "Name 3": Series([9, 10, 11, 12])}
df = pd.DataFrame(data)
df

,Name 1,Name 2,Name 3
0,1,5,9
1,2,6,10
2,3,7,11
3,4,8,12


In [57]:
# Словарь словарей
data = {"Name 1": {"Age": 23, "Salary": 10000},
                 "Name 2": {"Age": 24, "Salary": 20000},
                 "Name 3": {"Age": 25, "Salary": 30000}}
df = pd.DataFrame(data)
df

,Name 1,Name 2,Name 3
Age,23,24,25
Salary,10000,20000,30000


In [58]:
# Список объектов Series
arr = [Series([1, 2, 3, 4]), Series([5, 6, 7, 8]), Series([9, 10, 11, 12])]
df = pd.DataFrame(arr)
df

,0,1,2,3
0,1,2,3,4
1,5,6,7,8
2,9,10,11,12


In [59]:
# Список списков
arr = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
df = pd.DataFrame(arr)
df

,0,1,2,3
0,1,2,3,4
1,5,6,7,8
2,9,10,11,12


In [60]:
# Другой объект DataFrame
df1 = pd.DataFrame(data=[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
df = pd.DataFrame(df1)
df

,0,1,2,3
0,1,2,3,4
1,5,6,7,8
2,9,10,11,12


In [61]:
# Объект Numpy MaskedArray
arr = np.array([1, 2, 4, 5, 100])
arr_masked = np.ma.masked_equal(arr, 100)
df = pd.DataFrame(arr_masked)
df

,0
0,1.0
1,2.0
2,4.0
3,5.0
4,NaN


## Индексные объекты

В индексных объектах pandas хранятся метки вдоль осей и прочие метаданные (например, имена осей). Любой массив
или иная последовательность меток, указанная при конструировании Series или DataFrame, преобразуется в объект Index:

In [62]:
import pandas as pd
from pandas import Series

obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [63]:
index[1:]

Index(['b', 'c'], dtype='object')

Индексные объекты неизменяемы, т.е. пользователь не может их модифицировать:

In [64]:
index[1] = 'd'

TypeError: Index does not support mutable operations

Неизменяемость важна, для того чтобы несколько структур данных могли совместно использовать один и тот же
индексный объект, не опасаясь его повредить:

In [65]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [66]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [67]:
obj2.index is labels

True

Индексный объект не только похож на массив, но и ведет себя как множество фиксированного размера:

In [68]:
frame3

state,Nevada,Ohio
year,,
2001,2.4,1.7
2002,2.9,3.6
2000,NaN,1.5


In [69]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [70]:
'Ohio' in frame3.columns

True

In [71]:
2003 in frame3.index

False

В отличие от множеств Python, индекс в pandas может содержать повторяющиеся метки:

In [72]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

Если при выборе указана повторяющаяся метка, то будут выбраны все элементы с такой меткой.

У любого объекта Index есть ряд свойств и методов для ответа на типичные вопросы о хранящихся в нем данных.

Методы и свойства объекта Index: append; diff; intersection; union; isin; delete; drop; insert; is_monotonic; is_unique; unique.

## Задание 2

Приведите практические примеры всех методов и свойств объекта Index со своими примерами, перечисленных выше. В
отдельной строке перед примером необходимо дать описание каждого метода и свойства.

In [73]:
# append - добавление нового элемента
labels = pd.Index(["label 1", "label 2"])
new_labels = labels.append(pd.Index(["label 3"]))
new_labels

Index(['label 1', 'label 2', 'label 3'], dtype='object')

In [74]:
# diff - вычисление разности между элементами (параметр настраиваемый)
indices = pd.Index([0, 2, 4, 6, 8, 9, 10])
indices.diff()

Index([nan, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0], dtype='float64')

In [75]:
# intersection - пересечение значений двух объектов Index
indices2 = pd.Index([2, 4, 6, 8])
indices.intersection(indices2)

Index([2, 4, 6, 8], dtype='int64')

In [76]:
# union - объединение значений двух объектов Index
indices.union(indices2)

Index([0, 2, 4, 6, 8, 9, 10], dtype='int64')

In [77]:
# isin - проверка вхождения элемента в Index
indices.isin([2, 4, 6, 8])

array([False,  True,  True,  True,  True, False, False])

In [78]:
# delete - удаление элемента по позиции
indices.delete(1)

Index([0, 4, 6, 8, 9, 10], dtype='int64')

In [79]:
# drop - удаление элемента по значению
indices.drop(2)

Index([0, 4, 6, 8, 9, 10], dtype='int64')

In [80]:
# insert - Добавление элемента на позицию
indices.insert(1, 1)

Index([0, 1, 2, 4, 6, 8, 9, 10], dtype='int64')

In [81]:
# is_monotonic - проверка монотонности Index
print(indices.is_monotonic_increasing)
print(indices.is_monotonic_decreasing)

True
False


In [82]:
# is_unique - проверка уникальности элементов внутри Index
indices.is_unique

True

In [83]:
# unique - возвращает уникальные элементы Index
indices.unique()

Index([0, 2, 4, 6, 8, 9, 10], dtype='int64')