### Основы NumPy: массивы и векторные вычисления

Numerical Python (NumPy) - один из важнейших пакетов для численных расчетов в Python.
Рассмотрим массив NumPy, содержащий миллион чисел и эквивалентный список Python.


In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


Умножим каждую последовательность на 2:

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 12.2 ms, sys: 3.93 ms, total: 16.2 ms
Wall time: 15 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 256 ms, sys: 148 ms, total: 404 ms
Wall time: 404 ms


In [4]:
arr = np.random.rand(3, 6)
arr2 = np.random.rand(6, 3)

arr.T

array([[0.0087139 , 0.50500911, 0.40492762],
       [0.99797506, 0.8994645 , 0.72427801],
       [0.92564339, 0.16386398, 0.6969512 ],
       [0.22380665, 0.74551829, 0.71530466],
       [0.46423908, 0.11713874, 0.3508769 ],
       [0.78754379, 0.52810937, 0.96959962]])

Алгоритмы, основанные на NumPy, в общем случае оказываются намного быстрее аналогов, написанных на чистом
Python, и используют меньше памяти.


### NumPy ndarray: объект многомерного массива

Объект ndarray используется для представления N-мерного массива. Это контейнер для хранения больших наборов
данных в Python.


Сгенерируем небольшой массив случайных данных:

In [5]:
import numpy as np
# Генерация случайных данных
data = np.random.rand(2,3)
data

array([[0.50617149, 0.02000002, 0.12610641],
       [0.17178913, 0.49217767, 0.00068505]])

Математические операции над data:



In [6]:
data * 10

array([[5.06171492, 0.20000016, 1.26106406],
       [1.71789132, 4.92177667, 0.00685054]])

In [7]:
data + data

array([[1.01234298, 0.04000003, 0.25221281],
       [0.34357826, 0.98435533, 0.00137011]])

ndarray - это обобщенный многомерный контейнер для однородных данных, т.е. в нем могут храниться только элементы
одного типа. У любого массива есть атрибут shape - кортеж, который описывает размер по каждому измерению, и атрибут
dtype - объект, описывающий тип данных в массиве:


In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

### Создание ndarray

Самый просто способ создать массив - использовать функцию array. Она принимает любой объект, похожий на
последовательность (в том числе другой массив), и порождает новый массив NumPy, который содержит переданные
данные.

Преобразование списка:


In [10]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1


array([6. , 7.5, 8. , 0. , 1. ])

Вложенные последовательности, например, список списков одинаковой длины, можно преобразовать в многомерный
массив:


In [11]:
import numpy as np
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

data2 - список списков, поэтому массив import NumPy arr2 имеет два значения, а его форма выведена из данных. Это
можно посмотреть через атрибуты ndim и shape:

In [12]:
arr2.ndim


2

In [13]:
arr2.shape

(2, 4)

Если явно не задано противное, то функция np.array пытается самостоятельно определить подходящий тип данных для
создаваемого массива. Этот тип данных хранится в специальном объекте dtype.


In [14]:
arr1.dtype


dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

Существует ряд других функций для создания массивов. Например, zeros и ones создают массивы заданной длины,
состоящие из нулей и единиц. shape.empty создает массив, не инициализируя его элементы.


In [16]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
import numpy as np
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Функция arange - это аналог встроенной функции в Python - range, только возвращаемым значением является массив:

In [18]:
import numpy as np
np.arange(15)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

NumPy ориентирован на числовые расчеты. Если тип данных не указан явно, во многих случаях это float64

### Тип данных для ndarray

dtype (тип данных) - специальный объект, который содержит информацию (метаданные), необходимую для интерпретации
содержимого блока памяти:

In [19]:
import numpy as np
arr1 = np.array([2, 4, 6], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [20]:
arr1.dtype


dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

Существует возможность преобразовать (привести) массив одного типа к другому с помощью метода astype:

In [22]:
import numpy as np
arr = np.array([2, 4, 6, 8, 10])
arr.dtype

dtype('int64')

In [23]:
float_arr = arr.astype(np.float64)
float_arr.dtype


dtype('float64')

Приведение чисел с плавающей точкой к целому типу:

In [24]:
import numpy as np
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr


array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [25]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

Если есть массив строк с целыми числами, то astype может преобразовать их в числовую форму:

In [26]:
import numpy as np
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)


array([ 1.25, -9.6 , 42.  ])

Есть одно но, при работе с np.string_ входные данные могут быть обрезаны, так как в NumPy размер строковых данных
фиксирован.

Можно использовать атрибут dtype другого массива:

In [27]:
import numpy as np
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Арифметические операции в NumPy

Массивы позволяют выразить операции над совокупностями данных без выписывания циклов for. Обычно это называется
векторизацией. Любая арифметическая операция над массивами одинакового размера применяется к соответственным
элементам.


In [28]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr - arr


array([[0., 0., 0.],
       [0., 0., 0.]])

Арифметические операции, в которых участвует скаляр, применяются к каждому элементу массива:

In [31]:
1 / arr


array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Сравнение одинакового размера дает булев массив:

In [33]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Индексирование и вырезание

Одномерные массивы, по большей части, ведут себя как списки Python:

In [35]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5]

np.int64(5)

In [37]:
arr[5:8]

array([5, 6, 7])

Если присвоить скалярное значение срезу, то оно распространяется (укладывается) на весь срез:

In [38]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Отличие от списков состоит в том, что срез массива - представление исходного массива. Это означает, что данные на
самом деле не копируются, а любые изменения, внесенные в представление, попадают в исходный массив.


In [39]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Если изменить значения в arr_slice, то изменения отразятся на исходном массиве arr:

In [40]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

Присвоение неуточненному срезу [:] приводит к записи значения во все элементы массива:

In [41]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Чтобы получить копию, а не представление среза массива, нужно выполнить операцию копирования явно, например,
arr[5:8].copy()

В случае двумерного массива, результатом индексирования с одним индексом является не скаляр, а одномерный массив:

In [42]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

К отдельным элементам можно обращаться рекурсивно. Но это слишком громоздко, поэтому для выбора одного элемента можно указать список индексов через запятую. Таким образом, следующие конструкции эквивалентны:

In [43]:
arr2d[0][2]

np.int64(3)

In [44]:
arr2d[0, 2]

np.int64(3)

Если при работе с многомерным массивом опустить несколько последних индексов, то будет возвращен объект ndarray
меньшей размерности, содержащий данные по указанным при индексировании осям. Например, пусть имеется массив
arr3d размерности 2х2х3:


In [45]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Тогда arr3d[0] - массив размерности 2х2:

In [46]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Выражению arr3d[0] можно присвоить как скалярное значение, так массив:


In [47]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Аналогично arr3d[1, 0] дает все значения, список индексов которых начинается с (0, 1), т.е. одномерный массив:

In [49]:
arr3d[1, 0]

array([7, 8, 9])

Такой же результат мы подучим, если будем индексировать в два приема:


In [50]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [51]:
x[0]


array([7, 8, 9])

Во всех случаях, когда выбираются участки массива, результатом является представление

### Индексирование срезами

Как и для одномерных объектов наподобие списков Python, для объектов ndarray можно формировать срезы:

In [52]:
arr


array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
arr[1:6]


array([ 1,  2,  3,  4, 64])

Рассмотрим приведенный выше двумерный массив arr2d. Применение к нему вырезания даст иной результат:

In [54]:
arr2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

Вырезание производится вдоль оси 0, первой оси. Поэтому срез содержит диапазон элементов вдоль этой оси.
Выражение arr2d[:2] можно прочитать как: выбрать первые две строчки arr2d.

Можно указать несколько срезов - как несколько индексов:


In [56]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

При таком вырезании всегда получается представление массивов с таким же числом измерений, как у исходного. Сочетая
срезы и целочисленные индексы, можно получить массивы меньшей размерности.

Например, можно выбрать вторую строку, а в ней только первые два столбца:

In [57]:
arr2d[1, :2]

array([4, 5])

Можно выбрать третий столбец, а в нем только первые две строки:

In [58]:
arr2d[:2, 2]

array([3, 6])

Двоеточие без указания числа означает, что нужно взять всю ось целиком, поэтому для получения осей только высших
размерностей можно сделать так:

In [59]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

Присваивание выражению-срезу означает присваивание всем элементам этого среза:

In [60]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Булево индексирование

Пусть имеется некоторый массив с данными и массив имен, содержащий дубликаты. Необходимо воспользоваться
функцией randn из модуля numpy.random, чтобы сгенерировать случайные данные с нормальным распределением:

In [61]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [62]:
data

array([[-1.93976469, -1.99401834,  0.60084518, -1.82447271],
       [-2.23111706, -2.48385593, -0.2012218 , -0.90433676],
       [-0.42968053,  1.10194462,  0.10609014,  0.72058875],
       [-0.13245704, -0.69965552,  0.07602868, -0.73871494],
       [ 1.61996905,  0.47871203,  0.49060601,  0.86024664],
       [ 0.4015484 , -2.89774128,  0.05509235, -0.36269428],
       [-1.70822198, -1.38506661,  1.89462846, -0.978952  ]])

Допустим, что каждое имя соответствует строке в массиве data, мы хотим выбрать все строки, которым соответствует 'Bob'.
Операции сравнения массивов (например, ==), как и арифметические, также векторизованы. Поэтому сравнение name
со строкой 'Bob' дает массив булевых величин:

In [63]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

Этот булев массив можно использовать для индексирования другого массива:

In [64]:
data[names == 'Bob']

array([[-1.93976469, -1.99401834,  0.60084518, -1.82447271],
       [-0.13245704, -0.69965552,  0.07602868, -0.73871494]])

Длина булева массива должна совпадать с длиной индексируемой им оси. Можно сочетать булевы массивы со срезами и
целыми числами (или последовательностями целых чисел):

Выберем строки в которых names == 'Bob' и одновременно зададим индекс столбцов:

In [65]:
data[names == 'Bob', 2:]

array([[ 0.60084518, -1.82447271],
       [ 0.07602868, -0.73871494]])

In [66]:
data[names == 'Bob', 2]


array([0.60084518, 0.07602868])

Чтобы выбрать все кроме 'Bob' можно либо воспользоваться оператором сравнения !=, либо применить отрицание
условия, обозначаемое -

In [67]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [68]:
data[~(names == 'Bob')]

array([[-2.23111706, -2.48385593, -0.2012218 , -0.90433676],
       [-0.42968053,  1.10194462,  0.10609014,  0.72058875],
       [ 1.61996905,  0.47871203,  0.49060601,  0.86024664],
       [ 0.4015484 , -2.89774128,  0.05509235, -0.36269428],
       [-1.70822198, -1.38506661,  1.89462846, -0.978952  ]])

Если требуется инвертировать условие общего вида, то необходимо использовать ~

In [69]:
cond = names == 'Bob'
data[~cond]

array([[-2.23111706, -2.48385593, -0.2012218 , -0.90433676],
       [-0.42968053,  1.10194462,  0.10609014,  0.72058875],
       [ 1.61996905,  0.47871203,  0.49060601,  0.86024664],
       [ 0.4015484 , -2.89774128,  0.05509235, -0.36269428],
       [-1.70822198, -1.38506661,  1.89462846, -0.978952  ]])

Чтобы сформировать составное булево условие, включающее два из трех имен, необходимо воспользоваться булевыми
операторами &(И) и |(ИЛИ):

In [70]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [71]:
data[mask]

array([[-1.93976469, -1.99401834,  0.60084518, -1.82447271],
       [-0.42968053,  1.10194462,  0.10609014,  0.72058875],
       [-0.13245704, -0.69965552,  0.07602868, -0.73871494],
       [ 1.61996905,  0.47871203,  0.49060601,  0.86024664]])

При выборке данных из массива путем булева индексирования всегда создается копия данных, даже если возвращенный
массив совпадает с исходным.

Ключевые слова Python and и or с булевыми массивами не работаю. Вместо них необходимо использовать &(И) и |(ИЛИ).

Чтобы заменить все отрицательные значения в массиве data нулем:

In [72]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.60084518, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.10194462, 0.10609014, 0.72058875],
       [0.        , 0.        , 0.07602868, 0.        ],
       [1.61996905, 0.47871203, 0.49060601, 0.86024664],
       [0.4015484 , 0.        , 0.05509235, 0.        ],
       [0.        , 0.        , 1.89462846, 0.        ]])

Задание целых строк или столбцов с помощью одномерного булева массива:


In [73]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.4015484 , 0.        , 0.05509235, 0.        ],
       [0.        , 0.        , 1.89462846, 0.        ]])

### Fancy indexing (Индексирование с помощью целочисленных массивов.)

Допустим, имеется массив 8х4:

In [74]:
import numpy as np
arr = np.empty((8, 4))
for i in range(8):
 arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

Чтобы выбрать подмножество строк в определенном порядке, можно передать список или массив целых чисел,
описывающих желаемый порядок:


In [75]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Если указать отрицательный индекс, то номер соответствующей строки будет отсчитываться с конца:

In [76]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

При передаче нескольких массивов индексов делается несколько иное: выбирается одномерный массив элементов,
соответствующих каждому кортежу индексов:

In [77]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [78]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Здесь отбираются элементы в позициях (0, 1), (5, 3), (7, 1) и (2, 2). Вне зависимости от количества измерений массива (в
данном случае) результат всегда одномерный.

Данный вид индексирования всегда порождает новый массив, в который копируются данные

### Транспонирование и перестановка осей

Транспонирование - частный случай изменения формы, при этом также возвращается представление исходных данных без
какого-либо копирования. У массивов имеется метод transpose и специальный атрибут Т:

In [79]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Вычисление матрицы ХХ с помощью метода np.dot:

In [81]:
import numpy as np
arr = np.random.rand(6, 3)
arr

array([[0.65365069, 0.492935  , 0.99727238],
       [0.66474881, 0.36533183, 0.02687015],
       [0.51018889, 0.18123725, 0.98693175],
       [0.53086753, 0.32840227, 0.67922354],
       [0.22320671, 0.67300903, 0.98456939],
       [0.31644698, 0.56670217, 0.50732549]])

In [82]:
np.dot(arr.T, arr)

array([[1.56122318, 1.16141586, 1.91413314],
       [1.16141586, 1.29123975, 1.85346087],
       [1.91413314, 1.85346087, 3.65740915]])

Для массивов большей размерности метод transpose принимает кортеж номеров осей, описывающих их перестановку:


In [83]:
import numpy as np
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
arr.transpose((1, 0, 2))


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Здесь изменен порядок осей: вторая ось стала первой, первая - второй, а третья осталась неизменной.

Обычное транспонирование с помощью .Т - частный случай перестановки осей. У объекта ndarray имеется метод
swapaxes, который принимает пару номеров осей и меняет их местами, в результате чего, данные реорганизуются:

In [85]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [86]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

Метод swapaxes также возвращает представление без копирования данных.