## Универсальные функции

Универсальная функция (u-функция) - это функция, которая выполняет поэлементные операции над данными, которые
хранятся в объектах ndarray.

In [1]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr = np.random.randint(3, 10, size=(3,6))
arr

array([[5, 7, 3, 7, 6, 8],
       [7, 9, 9, 4, 5, 7],
       [8, 3, 9, 8, 9, 7]])

In [3]:
maximum = np.max(arr)
arr[arr == maximum] = -100
arr

array([[   5,    7,    3,    7,    6,    8],
       [   7, -100, -100,    4,    5,    7],
       [   8,    3, -100,    8, -100,    7]])

In [4]:
arr.cumprod(axis=1)

array([[       5,       35,      105,      735,     4410,    35280],
       [       7,     -700,    70000,   280000,  1400000,  9800000],
       [       8,       24,    -2400,   -19200,  1920000, 13440000]])

In [5]:
np.sqrt(arr)

/tmp/ipykernel_33103/1450069282.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[2.23606798, 2.64575131, 1.73205081, 2.64575131, 2.44948974,
        2.82842712],
       [2.64575131,        nan,        nan, 2.        , 2.23606798,
        2.64575131],
       [2.82842712, 1.73205081,        nan, 2.82842712,        nan,
        2.64575131]])

In [6]:
np.exp(arr)

array([[1.48413159e+02, 1.09663316e+03, 2.00855369e+01, 1.09663316e+03,
        4.03428793e+02, 2.98095799e+03],
       [1.09663316e+03, 3.72007598e-44, 3.72007598e-44, 5.45981500e+01,
        1.48413159e+02, 1.09663316e+03],
       [2.98095799e+03, 2.00855369e+01, 3.72007598e-44, 2.98095799e+03,
        3.72007598e-44, 1.09663316e+03]])

Такие функции называются унарными. Другие, например add или maximum, принимают два массива (и поэтому
называются бинарными) и возвращают один результирующий массив.

In [7]:
import numpy as np

x = np.random.randn(8)
y = np.random.randn(8)
x

array([-1.0201726 , -0.08422916, -0.60591746,  0.9884157 ,  1.09444756,
        0.50381102,  0.69965405, -1.33161543])

In [8]:
y

array([-1.43283544,  0.33548279,  0.2073181 , -0.08796034,  1.22346725,
       -1.41284519, -1.59321625, -0.22092564])

In [9]:
np.maximum(x, y)

array([-1.0201726 ,  0.33548279,  0.2073181 ,  0.9884157 ,  1.22346725,
        0.50381102,  0.69965405, -0.22092564])

numpy.maximum вычисляет поэлементные максимумы в массивах x и y.

Также существуют функции, которые возвращают несколько массивов. Например, modf - векторный вариант встроенной
в Python функции divmod, которая возвращает дробные и целые части, которые хранятся в массиве чисел с плавающей
точки.

In [10]:
import numpy as np

arr = np.random.randn(7) * 5
arr

array([-3.6429751 , -4.92006669,  2.34688078, 11.64444201, -4.82798691,
        1.51577133,  2.7759038 ])

In [11]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.6429751 , -0.92006669,  0.34688078,  0.64444201, -0.82798691,
        0.51577133,  0.7759038 ])

In [12]:
whole_part

array([-3., -4.,  2., 11., -4.,  1.,  2.])

U-функция принимает необязательный аргумент out, который позволяет выполнять операции над массивами на месте:

In [13]:
arr

array([-3.6429751 , -4.92006669,  2.34688078, 11.64444201, -4.82798691,
        1.51577133,  2.7759038 ])

In [14]:
np.sqrt(arr)

/tmp/ipykernel_33103/1450069282.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 1.53195326, 3.41239535,        nan,
       1.23116666, 1.66610438])

In [15]:
np.sqrt(arr, arr)

/tmp/ipykernel_33103/1787379640.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan,        nan, 1.53195326, 3.41239535,        nan,
       1.23116666, 1.66610438])

In [16]:
arr

array([       nan,        nan, 1.53195326, 3.41239535,        nan,
       1.23116666, 1.66610438])

Унарные u-функции: abs, fabs; sqrt; square; exp; log, log10, log2, log1p; sign; ceil; floor; rint; modf; isnan; isfinite, isinf; cos,
cosh, sin, sinh, tan, tanh; arccos, arccosh, arcsin, arcsinh, arctan, arctanh; logical_not

Бинарные u-функции: add; subtract; multiply; divide, floor_divide; power; maximum, fmax; minimum, fmin; mod; copysign;
greater, greater_equal, less, less_equal, equal, not_equal; logical_and; logical_or; logical_xor.

### Задание 1:

1. Приведите практические примеры всех унарных функций, перечисленных выше. В отдельной строке перед примером необходимо дать описание каждой функции.
2. Приведите практические примеры всех бинарных функций, перечисленных выше. В отдельной строке перед примером необходимо дать описание каждой функции.

In [17]:
# Функции фильтрации ndarray
arr = np.arange(-10, 10)
arr_positive = arr[arr > 0].copy()
arr_float = np.arange(-10.5, 10.5, 2)
arr_comlex = np.array([1 + 2j, 2 + 3j, 3 + 4j])
print(arr)
print(arr_positive)
print(arr_float)
print(arr_comlex)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
[1 2 3 4 5 6 7 8 9]
[-10.5  -8.5  -6.5  -4.5  -2.5  -0.5   1.5   3.5   5.5   7.5   9.5]
[1.+2.j 2.+3.j 3.+4.j]


In [18]:
# abs - Вычисляет абсолютные значения каждого элемента массива, сохраняет исходный тип данных (поддерживает int, float, и комплексные числа)
print(np.abs(arr))
print(np.abs(arr_float))
print(np.abs(arr_comlex))

[10  9  8  7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9]
[10.5  8.5  6.5  4.5  2.5  0.5  1.5  3.5  5.5  7.5  9.5]
[2.23606798 3.60555128 5.        ]


In [19]:
# fabs - Вычисляет абсолютные значения каждого элемента массива, возвращает всегда float (поддерживает int и float)
print(np.fabs(arr))
print(np.fabs(arr_float))
#print(np.fabs(arr_comlex))

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.  0.  1.  2.  3.  4.  5.  6.  7.
  8.  9.]
[10.5  8.5  6.5  4.5  2.5  0.5  1.5  3.5  5.5  7.5  9.5]


In [20]:
# sqrt - Вычисляет квадратный корень из каждого элемента массива (эквивалентно arr ** 0.5)
print(arr_positive)
np.sqrt(arr_positive)

[1 2 3 4 5 6 7 8 9]


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [21]:
# square - Вычисляет квадрат каждого элемента массива (эквивалентно arr ** 2)
np.square(arr)

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0,   1,   4,
         9,  16,  25,  36,  49,  64,  81])

In [22]:
# exp - Вычисляет экспоненту от каждого элемента массива
np.exp(arr)

array([4.53999298e-05, 1.23409804e-04, 3.35462628e-04, 9.11881966e-04,
       2.47875218e-03, 6.73794700e-03, 1.83156389e-02, 4.97870684e-02,
       1.35335283e-01, 3.67879441e-01, 1.00000000e+00, 2.71828183e+00,
       7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03])

In [23]:
# log, log10, log2, log1p - Вычисляет натуральный, десятичный логарифмы, логарифм по основанию 2 и log(1+x), соответственно
print(np.log(arr_positive))
print(np.log10(arr_positive))
print(np.log2(arr_positive))
print(np.log1p(arr_positive))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458 2.30258509]


In [24]:
# sign - Вычисляет знак каждого элемента: 1 (положительный элемент), 0 (ноль), −1 (отрицательный элемент)
np.sign(arr)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  1,  1,  1,  1,  1,  1,
        1,  1,  1])

In [25]:
# ceil - Вычисляет наименьшее целое число большее либо равное каждого элемента массива
print(arr_float)
np.ceil(arr_float)

[-10.5  -8.5  -6.5  -4.5  -2.5  -0.5   1.5   3.5   5.5   7.5   9.5]


array([-10.,  -8.,  -6.,  -4.,  -2.,  -0.,   2.,   4.,   6.,   8.,  10.])

In [26]:
# floor - Вычисляет наибольшее целое число меньшее либо равное каждого элемента массива
np.floor(arr_float)

array([-11.,  -9.,  -7.,  -5.,  -3.,  -1.,   1.,   3.,   5.,   7.,   9.])

In [27]:
# rint - Округляет элементы к ближайшим целым сохраняя dtype
np.rint(arr_float)

array([-10.,  -8.,  -6.,  -4.,  -2.,  -0.,   2.,   4.,   6.,   8.,  10.])

In [28]:
# modf - Возвращает дробные и целые части каждого элемента массива
fractional, whole = np.modf(arr_float)
print(whole)
print(fractional)

[-10.  -8.  -6.  -4.  -2.  -0.   1.   3.   5.   7.   9.]
[-0.5 -0.5 -0.5 -0.5 -0.5 -0.5  0.5  0.5  0.5  0.5  0.5]


In [29]:
# isnan - Возвращает булев массив, указывающий является ли каждый элемент входного массива NaN (Not A Number)
print(arr_float)
print(np.isnan(arr_float))
arr_mixed = np.array([1, np.nan, 3, 4, np.inf, 6])
print(np.isnan(arr_mixed))

[-10.5  -8.5  -6.5  -4.5  -2.5  -0.5   1.5   3.5   5.5   7.5   9.5]
[False False False False False False False False False False False]
[False  True False False False False]


In [30]:
# isfinite, isinf - Возвращает булев массив, указывающий является ли каждый элемент конечным (не inf и не NaN) или бесконечным, соответственно
print(arr_mixed)
print(np.isfinite(arr_mixed))
print(np.isinf(arr_mixed))

[ 1. nan  3.  4. inf  6.]
[ True False  True  True False  True]
[False False False False  True False]


In [31]:
# cos, cosh, sin, sinh, tan, tanh - тригонометрические функции(обычные и гиперболические)
print(np.cos(arr_float))
print(np.cosh(arr_float))
print(np.sin(arr_float))
print(np.sinh(arr_float))
print(np.tan(arr_float))
print(np.tanh(arr_float))

[-0.47553693 -0.6020119   0.97658763 -0.2107958  -0.80114362  0.87758256
  0.0707372  -0.93645669  0.70866977  0.34663532 -0.99717216]
[1.81577514e+04 2.45738452e+03 3.32571568e+02 4.50141201e+01
 6.13228948e+00 1.12762597e+00 2.35240962e+00 1.65728247e+01
 1.22348010e+02 9.04021484e+02 6.67986345e+03]
[ 0.87969576 -0.79848711 -0.21511999  0.97753012 -0.59847214 -0.47942554
  0.99749499 -0.35078323 -0.70554033  0.93799998 -0.07515112]
[-1.81577513e+04 -2.45738432e+03 -3.32570065e+02 -4.50030112e+01
 -6.05020448e+00 -5.21095305e-01  2.12927946e+00  1.65426273e+01
  1.22343923e+02  9.04020931e+02  6.67986338e+03]
[-1.84989999  1.32636433 -0.2202772  -4.63733205  0.7470223  -0.54630249
 14.10141995  0.37458564 -0.99558405  2.70601387  0.07536424]
[-1.         -0.99999992 -0.99999548 -0.99975321 -0.9866143  -0.46211716
  0.90514825  0.9981779   0.9999666   0.99999939  0.99999999]


In [32]:
# arccos, arccosh, arcsin, arcsinh, arctan, arctanh - обратные тригонометрические функции
print(np.arccos(arr_float))
print(np.arccosh(arr_float))
print(np.arcsin(arr_float))
print(np.arcsinh(arr_float))
print(np.arctan(arr_float))
print(np.arctanh(arr_float))

[      nan       nan       nan       nan       nan 2.0943951       nan
       nan       nan       nan       nan]
[       nan        nan        nan        nan        nan        nan
 0.96242365 1.9248473  2.38952643 2.70357583 2.94165731]
[        nan         nan         nan         nan         nan -0.52359878
         nan         nan         nan         nan         nan]
[-3.04678234 -2.83665573 -2.57081468 -2.20934771 -1.64723115 -0.48121183
  1.19476322  1.96572047  2.40605913  2.71246531  2.94719762]
[-1.47584462 -1.45368758 -1.418147   -1.35212738 -1.19028995 -0.46364761
  0.98279372  1.29249667  1.39094283  1.43824479  1.46591939]
[        nan         nan         nan         nan         nan -0.54930614
         nan         nan         nan         nan         nan]


/tmp/ipykernel_33103/155056002.py:2: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(arr_float))
/tmp/ipykernel_33103/155056002.py:3: RuntimeWarning: invalid value encountered in arccosh
  print(np.arccosh(arr_float))
/tmp/ipykernel_33103/155056002.py:4: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(arr_float))
/tmp/ipykernel_33103/155056002.py:7: RuntimeWarning: invalid value encountered in arctanh
  print(np.arctanh(arr_float))


In [33]:
# logical_not - Вычисляет истинное значение not x для каждого элемента
print(np.logical_not(arr))
arr_bool = np.array([True, False, True, False])
print(np.logical_not(arr_bool))

[False False False False False False False False False False  True False
 False False False False False False False False]
[False  True False  True]


In [34]:
# add - Складывает соответствующие элементы массивов
np.add(arr, arr)

array([-20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,
         6,   8,  10,  12,  14,  16,  18])

In [35]:
# substract - Вычитает соответствующие элементы второго массива из элементов первого
np.subtract(arr, arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
# multiply - Перемножает элементы массивов
np.multiply(arr, arr)

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0,   1,   4,
         9,  16,  25,  36,  49,  64,  81])

In [37]:
# divide, floor_devide - Деление или деление с отбрасыванием остатка
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = (arr1 * 2.75).copy()
print(np.divide(arr2, arr1))
print(np.floor_divide(arr2, arr1))

[2.75 2.75 2.75 2.75 2.75]
[2. 2. 2. 2. 2.]


In [38]:
# power - Возведение элементов первого массива в степени указанные во втором массиве
arr2 = np.array([2 for i in range(len(arr1))])
np.power(arr1, arr2)

array([ 1,  4,  9, 16, 25])

In [39]:
# maximum, fmax - Поэлементный максимум, fmax игнорирует NaN
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 1, np.nan, 5, 3])
print(np.maximum(arr1, arr2))
print(np.fmax(arr1, arr2))

[ 2.  2. nan  5.  5.]
[2. 2. 3. 5. 5.]


In [40]:
# minimum, fmin - Поэлементный минимум, fmin игнорирует NaN
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 1, np.nan, 5, 3])
print(np.minimum(arr1, arr2))
print(np.fmin(arr1, arr2))

[ 1.  1. nan  4.  3.]
[1. 1. 3. 4. 3.]


In [41]:
# mod - Поэлементный модуль (остаток от деления)
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 1, 4, 5, 3])
np.mod(arr2, arr1)

array([0, 1, 1, 1, 3])

In [42]:
# copysign - Копирует знаки элементов второго массива в элементы первого массива
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([-3, 4, -6, -7, 5])
np.copysign(arr1, arr2)

array([-1.,  2., -3., -4.,  5.])

In [43]:
# greater, greater_equal, less, less_equal, equal, not_equal - Поэлементное сравнение (эквивалентны операторам >, >=, <, <= `==`, !=)
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 3, 3, 6, 5])
print(np.greater(arr1, arr2))
print(np.greater_equal(arr1, arr2))
print(np.less(arr1, arr2))
print(np.less_equal(arr1, arr2))
print(np.equal(arr1, arr2))
print(np.not_equal(arr1, arr2))

[False False False False False]
[ True False  True False  True]
[False  True False  True False]
[ True  True  True  True  True]
[ True False  True False  True]
[False  True False  True False]


In [44]:
# logical_and, logical_or, logical_xor - Вычисляет поэлементное значение истинности логической операций (эквивалентны операторам &, ` | `, ^)
arr1 = np.array([1, 0, 3])
arr2 = np.array([2, 0, 0])

print(np.logical_and(arr1, arr2))
print(np.logical_or(arr1, arr2))
print(np.logical_xor(arr1, arr2))

[ True False False]
[ True False  True]
[False False  True]


## Программирование с применением массивов

С помощью NumPy многие виды обработки данных можно записать очень кратко, не прибегая к циклам. Такой способ
замены явных циклов выражениями-массивами обычно называется векторизацией. Векторные операции с массивами
выполняются в разы быстрее, чем эквивалентные операции на чистом Python.

Запись логических условий в виде операций над массивами

Функция numpy.where - это векторный вариант тернарного выражения x if condition else y. Пусть есть булев массив и два
массива значений:

In [45]:
import numpy as np

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Допустим, мы хотим брать значение из массива xarr, если соответственное значение в массиве cond равно True, а в
противном случае - значение из yarr. Это можно сделать при помощи операции спискового включения:

In [46]:
result = [(x if c else y)
for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

Почему так не надо:

1. Для больших массивов - это не быстро.
2. К многомерным массивам такое решение неприменимо.

Как надо:

In [47]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

Второй и третий аргументы np.where не обязаны быть массивами - один или оба могут быть скалярами. При анализе
данных where обычно применяются, чтобы создать новый массив на основе существующего.

Предположим, что имеется матрица со случайными данными и мы хотим заменить все положительные значения на 2, а
все отрицательные значения на -2.

In [48]:
import numpy as np

arr = np.random.randn(4, 4)
arr

array([[ 2.04199496, -0.01300845, -0.3224208 , -2.34616593],
       [-0.62135183,  0.925389  , -0.49591419,  1.74041394],
       [ 1.13428404, -0.53422466,  1.1737759 , -1.38010372],
       [-0.67262989, -0.13798059, -0.54451838, -0.83033836]])

In [49]:
arr > 0

array([[ True, False, False, False],
       [False,  True, False,  True],
       [ True, False,  True, False],
       [False, False, False, False]])

In [50]:
np.where(arr > 0, 2, -2)

array([[ 2, -2, -2, -2],
       [-2,  2, -2,  2],
       [ 2, -2,  2, -2],
       [-2, -2, -2, -2]])

In [51]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.01300845, -0.3224208 , -2.34616593],
       [-0.62135183,  2.        , -0.49591419,  2.        ],
       [ 2.        , -0.53422466,  2.        , -1.38010372],
       [-0.67262989, -0.13798059, -0.54451838, -0.83033836]])

Передавать where можно не только массивы одинакового размера или скаляры.

Математические и статистические операции

Среди методов NumPy есть математические функции для вычисления статистики массива в целом или данных вдоль оси.

Сгенерируем случайные данные с нормальным распределение и вычислим некоторые агрегаты:

In [52]:
import numpy as np

arr = np.random.randn(5, 4)
arr

array([[-0.94937223,  1.03324238,  1.12831634,  0.07204539],
       [ 0.32743178,  0.24700261,  0.71603905,  1.39452325],
       [-0.44362185, -0.57889556, -0.59066607, -0.29005697],
       [-0.14166611,  0.75619842, -0.36675269,  2.33532635],
       [ 2.35709415, -1.82747304, -2.51977127, -1.63741558]])

In [53]:
arr.mean()

np.float64(0.05107641721507337)

In [54]:
np.mean(arr)

np.float64(0.05107641721507337)

In [55]:
arr.sum()

np.float64(1.0215283443014673)

In [56]:
arr.mean(axis=1)

array([ 0.32105797,  0.67124917, -0.47581011,  0.64577649, -0.90689143])

In [57]:
arr.sum(axis=0)

array([ 1.14986574, -0.36992519, -1.63283464,  1.87442244])

In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

In [59]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [61]:
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]])

Статические методы массива: sum; mean; std, var; min, max; argmin, argmax; cumsum; cumprod.

## Задание 2:

Приведите практические примеры всех статических методов массива, перечисленных выше. В отдельной строке перед
примером необходимо дать описание каждого метода.

In [62]:
# sum - Сумма всех элементов массива или вдоль оси. Массив нулевой длины имеет сумму, равную 0
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(15).reshape(3, 5)
print(arr2)
print(arr.sum())
print(arr2.sum())
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
45
105
[15 18 21 24 27]
[10 35 60]


In [63]:
# mean - Арифметическое среднее
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(15).reshape(3, 5)
print(arr2)
print(arr1.mean())
print(arr2.mean())
print(arr2.mean(axis=0))
print(arr2.mean(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
3.0
7.0
[5. 6. 7. 8. 9.]
[ 2.  7. 12.]


In [64]:
# std, var - Стандартное отклонение и дисперсия, соответственно, с возможностью задания степени свободы (по умолчанию знаменатель равен n)
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.std())
print(arr1.var())

1.4142135623730951
2.0


In [65]:
# min, max - Минимум и максимум
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.min())
print(arr1.max())

1
5


In [66]:
# argmin, argmax - Индексы минимального и максимального элементов, соответственно
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.min())
print(arr1.max())

1
5


In [67]:
# cumsum - Накопленная сумма элементов, начиная с 0
arr1 = np.array([1, 2, 3, 4, 5])
arr1.cumsum()

array([ 1,  3,  6, 10, 15])

In [68]:
# cumprod - Накопленное произведение элементов, начиная с 1
arr1 = np.array([1, 2, 3, 4, 5])
arr1.cumprod()

array([  1,   2,   6,  24, 120])

## Методы булевых массивов

В методах выше булевы значения приводятся к 1 (True) и 0 (False), поэтому функция sum часто используется для
подсчета значений True в булевом массиве.

In [69]:
import numpy as np

arr = np.random.randn(100)
(arr > 0).sum() # количество положительных значений

np.int64(52)

Существует еще два метода: any и all. Они полезны в случае булевых массивов. Метод any проверяет, есть ли в массиве
хотя бы одно значение равное True, a all - все ли значения в массиве равны True.

In [70]:
import numpy as np

bools = np.array([False, False, True, False])
bools.any()

np.True_

In [71]:
bools.all()

np.False_

Данные методы работают также не для булевых массивов. В данном случае все отличные от нуля элементы считаются
равными True.

## Сортировка

Массивы в NumPy можно сортировать на месте методом sort.

In [72]:
import numpy as np

arr = np.random.randn(6)
arr

array([0.19113463, 0.00829988, 0.2487849 , 1.96852193, 0.25359911,
       0.44493129])

In [73]:
arr.sort()
arr

array([0.00829988, 0.19113463, 0.2487849 , 0.25359911, 0.44493129,
       1.96852193])

Любой одномерный участок многомерного массива можно отсортировать на месте, передав методу sort номер оси.

In [74]:
import numpy as np

arr = np.random.randn(5, 3)
arr

array([[-1.09162245,  0.74774306,  0.45572362],
       [-2.86959999,  1.58404058,  1.8521965 ],
       [-1.17470803, -0.08619031, -2.51498687],
       [-0.35724976,  1.31913691, -2.25416317],
       [-2.71966689,  0.58768565, -0.54623481]])

In [75]:
arr.sort(1)
arr

array([[-1.09162245,  0.45572362,  0.74774306],
       [-2.86959999,  1.58404058,  1.8521965 ],
       [-2.51498687, -1.17470803, -0.08619031],
       [-2.25416317, -0.35724976,  1.31913691],
       [-2.71966689, -0.54623481,  0.58768565]])

Метод верхнего уровня np.sort возвращает отсортированную копию массива, а не сортирует массив на месте. Например,
чтобы вычислить квантили массива, необходимо отсортировать его и выбрать значение с конкретным рангом:

In [76]:
import numpy as np

large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5%ый квантиль

np.float64(-1.7266285361389027)

## Удаление дубликатов и другие теоретико-множественные операции

np.unique - возвращает отсортированное множество уникальных значений в массиве:

In [77]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob',
                  'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [78]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4 ,4])
np.unique(ints)

array([1, 2, 3, 4])

In [79]:
sorted(set(names))

[np.str_('Bob'), np.str_('Joe'), np.str_('Will')]

Функция np.in1d проверяет наличие значений из одного массива в другом и возвращает булев массив.

In [80]:
import numpy as np

values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

/tmp/ipykernel_33103/3833642123.py:4: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2, 3, 6])


array([ True, False, False,  True,  True, False,  True])

Теоретико-множественные функции, имеющиеся в NumPy: unique(x); intersect1d(x, y); union1d(x, y); in1d(x, y); setdiff1d(x, y);
setxor1d(x, y).

## Задание 3:

Приведите практические примеры всех теоретико-множественных функций. В отдельной строке перед примером
необходимо дать описание каждой функции.

In [81]:
# unique(x) - Возвращает отсортированные единственные элементы из x
arr1 = np.array([1, 2, 2, 5, 5, 4, 6, 6, 6, 3])
np.unique(arr1)

array([1, 2, 3, 4, 5, 6])

In [82]:
# intersect1d(x, y) - Возвращает отсортированные общие элементы массивов x и y
arr1 = np.array([1, 2, 2, 5, 5, 4, 6, 6, 6, 3])
arr2 = np.array([1, 2, 3])

np.intersect1d(arr1, arr2)

array([1, 2, 3])

In [83]:
# union1d(x, y) - Возвращает отсортированное объединение элементов массивов x и y
arr1 = np.array([1, 2, 2, 5, 5, 4, 6, 6, 6, 3])
arr2 = np.array([1, 2, 3])

np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6])

In [84]:
# isin(x, y) - Возвращает булев массив, указывающий содержится ли каждый элемент массива x в y
arr1 = np.array([1, 2, 2, 5, 5, 4, 6, 6, 6, 3])
arr2 = np.array([1, 2, 3])

np.isin(arr1, arr2)

array([ True,  True,  True, False, False, False, False, False, False,
        True])

In [85]:
# setdiff1d(x, y) - Разность множеств: элементы массива x, которых нет в y
arr1 = np.array([1, 2, 2, 5, 5, 4, 6, 6, 6, 3])
arr2 = np.array([1, 2, 3])

np.setdiff1d(arr1, arr2)

array([4, 5, 6])

In [86]:
# setxor1d(x, y) - Симметричная разность: элементы, которые есть либо в x, либо в y, но не в обоих массивах
arr1 = np.array([1, 2, 2, 5, 5, 4, 6, 6, 6, 3])
arr2 = np.array([1, 2, 3])

np.setxor1d(arr1, arr2)

array([4, 5, 6])

## Файловый ввод-вывод массивов

NumPy умеет сохранять на диске и загружать с диска данные в текстовом или двоичном формате. Рассмотрим двоичный
формат, так с тестовым и табличным форматом лучше работать через pandas.

np.save и np.load - основные функции для эффективного сохранения и загрузки данных с диска. По умолчанию массивы
хранятся в несжатом двоичном формате в файле с расширением .npy.

In [87]:
import numpy as np

arr = np.arange(10)
np.save('some_array', arr)

Если путь к файлу не заканчивается суффиксом .npy, то последний будет добавлен. Хранящийся на диске массив можно
загрузить в память функцией np.load.

In [88]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Можно сохранить несколько массивов в zip-архиве с помощью функции np.saves, которой массивы передаются в виде
именованных аргументов.

In [89]:
np.savez('array_archive.npz', a=arr, b=arr)

In [90]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Если данные хорошо сжимаются, то можно вместо этого использовать метод numpy.savez_compressed.

In [91]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

## Линейная алгебра

Линейно-алгебраические операции: умножение и разложение матриц, вычисление определителей и другие - важная часть
любой библиотеки для работы с массивами. В отличие от некоторых языков, в NumPy применение оператора * к двум
двумерным массивам вычисляет поэлементное, а не матричное произведение. А для перемножения матриц имеется
функция dot - в виде как метода массива, так и функции в пространстве имен numpy.

In [92]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [93]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [94]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [95]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

x.dot(y) эквивалентно np.dot(x, y)

Произведение двумерного массива и одномерного массива подходящего размера дает одномерный массив.

In [96]:
np.dot(x, np.ones(3))

array([ 6., 15.])

Символ @ также может использоваться в роли инфиксного оператора умножения матриц.

In [97]:
x @ np.ones(3)

array([ 6., 15.])

В модуле numpy.linalg имеется стандартный набор алгоритмов, в частности, разложение матриц, нахождение обратной
матрицы и вычисление определителя.

In [98]:
from numpy.linalg import inv, qr

X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 0.71093908,  1.07463596, -1.30380892, -1.97998727, -0.64908989],
       [ 1.07463596,  2.50060887, -2.51045215, -3.9813872 , -1.72586426],
       [-1.30380892, -2.51045215,  2.94031729,  4.55791785,  1.77953718],
       [-1.97998727, -3.9813872 ,  4.55791785,  7.37542908,  3.1554901 ],
       [-0.64908989, -1.72586426,  1.77953718,  3.1554901 ,  2.33539166]])

In [99]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -9.88477059e-16,  1.72014769e-15,
        -6.40415908e-16,  7.45922959e-16],
       [ 4.60031163e-16,  1.00000000e+00, -1.28402595e-15,
         2.91277584e-16, -1.07765690e-15],
       [-3.04746679e-15, -5.31317398e-15,  1.00000000e+00,
         5.65103464e-15,  4.20096182e-15],
       [-4.30816685e-16, -4.32393882e-15,  9.05690834e-15,
         1.00000000e+00,  1.77434269e-15],
       [-1.64019008e-16, -5.05711298e-16, -3.63264184e-16,
         1.33961941e-15,  1.00000000e+00]])

In [100]:
q, r = qr(mat)
r

array([[ -9.73116281,  -1.41300392, -10.08277386,   2.73052876,
          0.28643198],
       [  0.        ,  -3.52593337,  -5.55683858,   1.9982421 ,
         -1.12863788],
       [  0.        ,   0.        , -11.7271284 ,   8.39743145,
         -2.47635744],
       [  0.        ,   0.        ,   0.        ,  -0.45762129,
          0.97675488],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.21330813]])

Выражение X.dot(X) вычисляет произведение матрицы X на транспонированную к ней матрицу Х.T.

## Генерация псевдо-случайных чисел

Модуль numpy.random дополняет встроенный модуль random функциями, которые генерируют целые массивы случайных
чисел с различными распределениями вероятности.

Получение случайного массива 4х4 с нормальным распределением.

In [101]:
import numpy as np

samples = np.random.normal(size=(4, 4))
samples

array([[ 2.57400448, -0.78805911, -0.2733614 , -0.77604778],
       [ 1.72473479, -0.32832479,  0.4916647 ,  0.04949706],
       [ 0.01824472,  0.44779531,  0.94649966, -1.82200041],
       [-2.35821567,  0.20251299, -0.07541274, -0.06971553]])

Встроенный в Python модуль random умеет выдавать только по одному случайному числу за одно обращение.
numpy.random на порядок быстрее стандартного модуля при генерации очень больших выборок.

In [102]:
from random import normalvariate

N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

403 ms ± 7.89 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [103]:
%timeit np.random.normal(size=N)

17.4 ms ± 164 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Числа называются псевдослучайными, потому что они генерируются детерминированным алгоритмом на основе
начального значения, которое можно изменить с помощью метода np.random.seed.

In [104]:
np.random.seed(1234)

In [105]:
import numpy as np

rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])